# Generated by Django 4.0.3 on 2022-09-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ram', models.CharField(max_length=100)),
                ('Rom', models.CharField(max_length=50)),
                ('Pri_cam', models.CharField(max_length=40)),
                ('sec_cam', models.CharField(max_length=40)),
                ('battery', models.CharField(max_length=40)),
                ('predictions', models.CharField(max_length=50)),
            ],
        ),
    ]
