# Generated by Django 4.1.1 on 2022-09-15 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0002_alter_data_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
