# Generated by Django 4.1.1 on 2022-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0004_alter_data_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mobile_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
