# Generated by Django 4.1.1 on 2022-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0006_alter_data_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Pri_cam',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='data',
            name='Ram',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Rom',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='battery',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='data',
            name='mobile_size',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='sec_cam',
            field=models.IntegerField(max_length=40),
        ),
    ]
