# Generated by Django 4.1.1 on 2022-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0008_alter_data_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Pri_cam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='Ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='Rom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='battery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='mobile_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='sec_cam',
            field=models.IntegerField(),
        ),
    ]
