# Generated by Django 4.1.1 on 2022-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0010_pre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelTable(
            name='data',
            table='model1_data',
        ),
    ]
