# Generated by Django 4.1.1 on 2022-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
                ('px_height', models.IntegerField()),
                ('battery_pow', models.IntegerField()),
                ('px_width', models.IntegerField()),
                ('mobile_wt', models.IntegerField()),
                ('int_mem', models.IntegerField()),
                ('sc_h', models.IntegerField()),
                ('talk_time', models.IntegerField()),
                ('sc_w', models.IntegerField()),
                ('fc', models.IntegerField()),
                ('n_core', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('predictions', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'com_data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
