# Generated by Django 4.1.1 on 2022-09-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companydata',
            table='company_data',
        ),
    ]
