# Generated by Django 4.1.1 on 2022-09-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyml', '0002_alter_companydata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pre',
        ),
    ]
