# Generated by Django 4.1.1 on 2022-09-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyml', '0003_delete_pre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydata',
            options={},
        ),
        migrations.AlterModelTable(
            name='companydata',
            table=None,
        ),
    ]
