# Generated by Django 4.1.1 on 2022-09-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyml', '0004_alter_companydata_options_alter_companydata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companyData',
        ),
    ]
